version: '3.8'

services:
  web:
    build: .
    container_name: healthtrack_web
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost  
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    image: postgres:13
    container_name: healthtrack_db
    environment:
      POSTGRES_DB: healthtrack
      POSTGRES_USER: healthtrackuser
      POSTGRES_PASSWORD: securepassword  
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: healthtrack_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build: .
    container_name: healthtrack_worker
    command: celery -A healthtrack worker --loglevel=info
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data: